version: '3.6'

services:
  app:
    image: ghost:alpine
    container_name: ghost_api
    ports:
      - 80:2368
    restart: on-failure
    depends_on:
      - db
    networks:
      - ghost-network

  db:
    image: mysql:5.7
    container_name: db_ghost
    environment:
      - database__client=mysql
      - database__connection_host=db
      - database__connection_user=root
      - database__connection_password=example
      - database__connection_database=ghost
    volumes:
      - db:/var/lib/mysql
    networks:
      - ghost-network

volumes:
  db:

# Networks to be created to facilitate communication between containers
networks:
  ghost-network:
    driver: bridge
