apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  TZ: Asia/Singapore
  POSTGRES_DB: registry
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |-
    CREATE TABLE book (
    	id SERIAL PRIMARY KEY NOT NULL,
    	owner_id int NOT NULL,
        name VARCHAR (255) UNIQUE NOT NULL,
    	description text,
    	creation_time timestamp default CURRENT_TIMESTAMP,
        update_time timestamp  default CURRENT_TIMESTAMP,
        deleted boolean DEFAULT false NOT NULL
    );