version: '3.8'

services:
  nodejs-service:
    image: demo-service:v2
    ports:
      - "8000:3000"
    networks:
      - mongodb-nodejs
    environment:
      MONGODB_URI: mongodb://mongodb:27017/demo
      PORT: 3000
    restart: on-failure
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    networks:
      - mongodb-nodejs

networks:
  mongodb-nodejs:
    driver: bridge

volumes:
  mongodb:
