#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: hostpath
#  annotations:
#    storageclass.kubernetes.io/is-default-class: "true"
#provisioner: kubernetes.io/no-provisioner
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    app: postgres
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: hostpath
  resources:
    requests:
      storage: 3Gi